src/main/webapp/app.js, src/main/webapp/css/colorTheme.css, src/main/webapp/css/navbarStyle.css, src/main/webapp/css/signUpStyle.css, src/main/webapp/index.html, src/main/webapp/javascript/controllers/navbarController.js, src/main/webapp/javascript/controllers/signUpController.js, src/main/webapp/javascript/directives.js, src/main/webapp/javascript/services.js, src/main/webapp/lib/angular-base64.min.js, src/main/webapp/templates/components/navbar.html, src/main/webapp/templates/signUp.html
- Added register page:
- Added controller #11 .
- Added css #13 .
-  Added html #13 .
- Added register service #11 .
- Added navbar app.
- Added an app color theme.
=> Add register page, navbar app and color theme

.travis.yml, src/test/java/RegistrationTest.java, src/test/java/SeleniumFirstTest.java
- Modify travis.yml to run Jetty on Travis
- Modify previous "SeleniumFirstTest" to "RegistrationTest" with a simple registration test with selenium.
=> Selenium tests working correctly on travis and simple registration test

src/main/webapp/app.js, src/main/webapp/css/exerciseCardStyle.css, src/main/webapp/index.html, src/main/webapp/javascript/controllers/exerciseCardController.js, src/main/webapp/javascript/controllers/homeController.js, src/main/webapp/javascript/directives.js, src/main/webapp/javascript/services.js, src/main/webapp/templates/components/exerciseCard.html, src/main/webapp/templates/home.html, src/main/webapp/templates/signUp.html, src/main/webapp/templates/starter.html
- Added home page and exercise cards:
- Added controller #24 .
- Added css #26 .
- Added html #26 .
- Added exercise service #24.
- Correct guide styles in front-end.
=> Add home page and exercise cards

src/main/resources/create-exercise&muscleGrop.sql, src/main/resources/populate-exercise&muscleGroup.sql
- Add create-exercise&muscleGroup.sql to create both tables. #21 
- Add populate-exercise&muscleGroup.sql to insert a few data on the DB. #21
=> Add new sql files for tables 'Exercise' and 'MuscleGroup'

src/test/java/org/trainingTracker/selenium/SignInTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java
- Add selenium tests for sign up operation #14 
- Add selenium tests for sign in operation #20
=> Add selenium tests with @ignore annotation

src/main/java/org/trainingTracker/servlets/SignIn.java, src/main/java/org/trainingTracker/servlets/SignUp.java, src/main/webapp/css/exerciseCardStyle.css, src/main/webapp/css/homeStyle.css, src/main/webapp/css/signUpStyle.css, src/main/webapp/css/starterStyle.css, src/main/webapp/index.html, src/main/webapp/javascript/controllers/exerciseCardController.js, src/main/webapp/javascript/controllers/homeController.js, src/main/webapp/javascript/services.js, src/main/webapp/templates/components/exerciseCard.html, src/main/webapp/templates/home.html
- Added save record modal:
- Added controller #30 .
- Added css #32 .
- Added html #32 .
- Added save record service #30 .
- Corrected some typos in feedback error messages in signUp and signIn servlets.
=> Add save record modal

README.md, src/main/java/org/trainingTracker/servlets/SignUp.java, src/main/webapp/templates/signUp.html, src/main/webapp/templates/starter.html, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java, src/test/java/org/trainingTracker/selenium/SignInTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java
- Some modifications and refactoring on selenium tests
- Fix SignUp servlet that wasn't working.
- Couple changes on html templates.
=> Modify selenium tests & fix signUp servlet

src/main/java/org/trainingTracker/servlets/ListPerformed.java, src/main/java/org/trainingTracker/servlets/SignIn.java, src/main/java/org/trainingTracker/servlets/SignUp.java
doGet and doPost in all servlets
=>  Added alternative call methods

src/main/webapp/templates/home.html, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java, src/test/java/org/trainingTracker/selenium/SignInTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java, src/test/java/org/trainingTracker/selenium/TestUtils.java
- Add a new 'TestUtils' class with common methods and attributes for some selenium tests.
- Modify fillArray method, now on 'TestUtils' class.
- Add new Selenium tests for SaveRecord. #33
=> New TestUtils class. Add new selenium tests for SaveRecord. Some refactoring.

deployDB.sql, src/main/java/org/trainingTracker/database/dataAccesObject/ExercisesDAO.java, src/main/java/org/trainingTracker/database/dataAccesObject/RecordsDAO.java, src/main/java/org/trainingTracker/database/dataAccesObject/UsersDAO.java, src/main/java/org/trainingTracker/servlets/ListPerformed.java, src/main/resources/03-create-exercises.sql, src/main/resources/04-create-records.sql, src/main/resources/903-populate-exercises.sql, src/test/java/org/trainingTracker/database/dataAccesObject/DAOMasterTest.java, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java
This PR implements the hability to delete specific entries on the data base.
=> Add Delete methods to Users, Exercises and Records. Add addDefault/CustomExercise to Homescreen 

src/main/webapp/app.js, src/main/webapp/css/addExerciseStyle.css, src/main/webapp/css/homeStyle.css, src/main/webapp/index.html, src/main/webapp/javascript/controllers/addExerciseController.js, src/main/webapp/javascript/services.js, src/main/webapp/templates/addExercise.html, src/main/webapp/templates/home.html
Added 'add exercise' page and app state:
- Added 'add predetermined exercise' functionallity:
- Added controller #37 .
- Added css #39  .
- Added html #39 .
- Added save record service #37 .
- Added 'add custom exercise' functionallity:
- Added controller #44 .
- Added css #47 .
- Added html #47 .
- Added save record service #44 .
=> Add addExercise page

src/test/java/org/trainingTracker/selenium/SaveRecordTest.java, src/test/java/org/trainingTracker/selenium/SignInTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java, src/test/java/org/trainingTracker/selenium/TestUtils.java
- Add some new selenium tests.
- Removes the 'ignore' annotation on all selenium tests.
- Selenium tests passing correctly on travis.
=> Add new selenium tests. Removes ignore annotation from selenium tests.

src/main/webapp/templates/addExercise.html, src/test/java/org/trainingTracker/selenium/AddCustomExerciseTest.java, src/test/java/org/trainingTracker/selenium/AddPredeterminedExerciseTest.java, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java, src/test/java/org/trainingTracker/selenium/SignInTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java, src/test/java/org/trainingTracker/selenium/TestUtils.java
- Add new selenium tests for new predetermined exercise #40 
- Add new selenium tests for new custom exercise #46 
- Some refactors on previous tests
=> Add new selenium test for new exercises

src/main/webapp/css/addExerciseStyle.css, src/main/webapp/css/homeStyle.css, src/main/webapp/javascript/controllers/addExerciseController.js, src/main/webapp/javascript/controllers/homeController.js, src/main/webapp/javascript/controllers/signUpController.js, src/main/webapp/templates/addExercise.html, src/main/webapp/templates/home.html, src/main/webapp/templates/signUp.html
- Added email input control length in signUp.
- Added record inputs control length in home.
- Added customName input control length in addExercise.
- Corrected problem with empty commentaries.
=> Add inputs control length

src/main/webapp/templates/addExercise.html, src/main/webapp/templates/home.html, src/main/webapp/templates/signUp.html, src/test/java/org/trainingTracker/selenium/AddCustomExerciseTest.java, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java
- Add new test on SignUpTest to check the maximum length on some fields.
- Add new test on SaveRecordTest to check the maximum length on some fields.
- Add new test on AddCustomExerciseTest to check the maximum length on some fields.
- Add new test on AddCustomExerciseTest to check the exercise name blank.
=> Add new selenium tests to check max length inputs

src/main/java/org/trainingTracker/database/dataAccesObject/ExercisesDAO.java, src/main/java/org/trainingTracker/servlets/AddExercise.java, src/main/java/org/trainingTracker/servlets/GetPredetermined.java, src/main/webapp/WEB-INF/web.xml
=> #36 Backend implementation (Add predetermined exercises)

src/main/webapp/templates/addExercise.html, src/test/java/org/trainingTracker/selenium/AddCustomExerciseTest.java, src/test/java/org/trainingTracker/selenium/AddPredeterminedExerciseTest.java, src/test/java/org/trainingTracker/selenium/TestUtils.java
- Fix some issues on AddCustomExercise and AddPredefinedExercise tests
- Fix some issues on addExercise HTML.
=> Couple fixes on add exercise tests and html

src/main/java/org/trainingTracker/database/dataAccesObject/ExercisesDAO.java, src/main/java/org/trainingTracker/servlets/AddExercise.java, src/main/java/org/trainingTracker/servlets/GetPredetermined.java, src/test/java/org/trainingTracker/database/dataAccesObject/DAOMasterTest.java
#36 Last part AddExercise servlet. Support for predetermined exercises added.
=> #36 Backend implementation (Add predetermined exercise)

src/main/java/org/trainingTracker/servlets/AddExercise.java, src/test/java/org/trainingTracker/selenium/AddCustomExerciseTest.java, src/test/java/org/trainingTracker/selenium/AddPredeterminedExerciseTest.java
- Add predetermined exercise tests without ignore annotation and couple changes
- AddExercise servlet fixed to correctly add new predetermined exercise to user's home
=> Couple changes on selenium tests + addExercise servlet fixed

.travis.yml, src/main/java/org/trainingTracker/database/dataAccesObject/ExercisesDAO.java, src/test/java/org/trainingTracker/selenium/AddCustomExerciseTest.java, src/test/java/org/trainingTracker/selenium/AddPredeterminedExerciseTest.java, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java, src/test/java/org/trainingTracker/selenium/SignInTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java
- Add cat command in travis.yml to log the output and error messages in travis
- Some log messages on tests
=> Add cat to travis.yml and minor changes

src/main/java/org/trainingTracker/database/dataAccesObject/UsersDAO.java, src/main/java/org/trainingTracker/servlets/SaveRecord.java, src/test/java/org/trainingTracker/selenium/AddCustomExerciseTest.java, src/test/java/org/trainingTracker/selenium/AddPredeterminedExerciseTest.java, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java
- Modify SaveRecord servlet to replace "," for "." in the "Weight" field.
- Add new tests in SaveRecordTest to check if a new record is not added if a field contains a character string instead of a number.
=> Minor change in saveRecord servlet. New tests for saveRecord

src/main/webapp/css/exerciseCardStyle.css, src/main/webapp/css/homeStyle.css, src/main/webapp/javascript/controllers/exerciseCardController.js, src/main/webapp/javascript/controllers/homeController.js, src/main/webapp/javascript/services.js, src/main/webapp/templates/components/exerciseCard.html, src/main/webapp/templates/home.html
- Added 'modify/remove exercise' functionallity:
- Added controller #90 .
- Added css #92.
- Added html #92.
=> Add modify/remove exercise modals

src/main/java/org/trainingTracker/database/dataAccesObject/UsersDAO.java, src/main/webapp/templates/components/exerciseCard.html, src/main/webapp/templates/home.html, src/test/java/org/trainingTracker/selenium/AddCustomExerciseTest.java, src/test/java/org/trainingTracker/selenium/AddPredeterminedExerciseTest.java, src/test/java/org/trainingTracker/selenium/DeleteExerciseTest.java, src/test/java/org/trainingTracker/selenium/ModifyExerciseTest.java, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java, src/test/java/org/trainingTracker/selenium/SignUpTest.java, src/test/java/org/trainingTracker/selenium/TestUtils.java
- Add deleteExerciseTest #93 
- Add modifyExerciseTest #93 
- Modify some older tests
- Modify some HTML templates
=> Add remove/modify exercise tests

src/main/webapp/css/homeStyle.css, src/main/webapp/templates/addExercise.html, src/main/webapp/templates/home.html
- Added 'search/filter exercises' functionallity:
- Added controller #95 .
- Added css #94 .
- Added html #94 .
=> Add search/filter exercises

src/main/webapp/templates/home.html, src/test/java/org/trainingTracker/selenium/FilterTest.java, src/test/java/org/trainingTracker/selenium/SaveRecordTest.java
- Add new tests for the exercises filters #96
=> Add tests for exercises filters

src/main/java/org/trainingTracker/database/dataAccesObject/ExercisesDAO.java, src/test/java/org/trainingTracker/database/dataAccesObject/ExercisesDAOTest.java
Adds stronger tests and new method for updating an exercise info
Implements #91
=> Add UPDATE EXERCISE and tests for Exercises

src/main/java/org/trainingTracker/database/valueObject/ExerciseVO.java, src/main/java/org/trainingTracker/servlets/AddExercise.java, src/main/java/org/trainingTracker/servlets/ListPerformed.java, src/main/java/org/trainingTracker/servlets/ModifyExercise.java, src/main/java/org/trainingTracker/servlets/RemoveExercise.java, src/main/java/org/trainingTracker/servlets/SaveRecord.java, src/main/java/org/trainingTracker/servlets/SignIn.java, src/main/java/org/trainingTracker/servlets/SignUp.java, src/main/webapp/WEB-INF/web.xml
#89 
ModifyExercise servlet and RemoveExercise servlet.
web.xml updated.
Messages charset are correct now.
=> #89 Backend implementation (Modify/remove exercise)

src/main/java/org/trainingTracker/servlets/ListRecordHistory.java, src/main/webapp/WEB-INF/web.xml
#98 
listRecordHistory servlet.
web.xml.
=> #98 Backend implementation (Exercise progress)

src/main/webapp/javascript/controllers/exerciseHistoryController.js
=> Correct format date

src/main/webapp/javascript/controllers/addExerciseController.js, src/main/webapp/javascript/controllers/exerciseHistoryController.js, src/main/webapp/javascript/services.js, src/main/webapp/templates/addExercise.html
- Added 'add new cardiovascular exercise' functionallity:
- Added controller #109 .
- Added css #111 .
- Added html #111 .
=> Client side: Add new cardiovascular exercise

build.gradle, src/main/java/org/trainingTracker/servlets/GetPredetermined.java, src/main/java/org/trainingTracker/servlets/RemoveExercise.java, src/main/java/org/trainingTracker/servlets/ServletCommon.java, src/main/java/org/trainingTracker/servlets/SignIn.java, src/test/java/org/trainingTracker/servlets/AddExerciseServletTest.java, src/test/java/org/trainingTracker/servlets/ListPerformedServletTest.java, src/test/java/org/trainingTracker/servlets/ModifyExerciseServletTest.java, src/test/java/org/trainingTracker/servlets/RemoveExerciseServletTest.java, src/test/java/org/trainingTracker/servlets/SaveRecordServletTest.java, src/test/java/org/trainingTracker/servlets/ServletTestUtils.java, src/test/java/org/trainingTracker/servlets/SignInServletTest.java, src/test/java/org/trainingTracker/servlets/SignUpServletTest.java
- Add mockito tests for SignIn, SignUp, AddExercise, ListPredetermined, ModifyExercise, RemoveExercise and SaveRecord servlets. #104 #105
=> Add new mockito tests for testing the servlets

src/main/java/org/trainingTracker/database/dataAccesObject/ExercisesDAO.java, src/main/java/org/trainingTracker/database/dataAccesObject/RecordsDAO.java, src/main/java/org/trainingTracker/database/dataAccesObject/UsersDAO.java, src/test/java/org/trainingTracker/database/dataAccesObject/ExercisesDAOTest.java, src/test/java/org/trainingTracker/database/dataAccesObject/RecordsDAOTest.java, src/test/java/org/trainingTracker/database/dataAccesObject/UsersDAOTest.java
Implements stronger tests for DB
Completes #103
=> Stronger tests in DB

deployDB.sql, src/main/java/org/trainingTracker/database/dataAccesObject/CardioExercisesDAO.java, src/main/java/org/trainingTracker/database/valueObject/CardioExerciseVO.java, src/test/java/org/trainingTracker/database/dataAccesObject/CardioExercisesDAOTest.java
It also includes other features like list, remove, etc.
Completes #110 and #113
=> DataModel and Implementation of Add new Cardiovascular exercise to Home

src/main/webapp/javascript/controllers/homeController.js, src/main/webapp/javascript/services.js, src/main/webapp/templates/addExercise.html, src/main/webapp/templates/exerciseHistory.html
- Corrected exercise lists due to the new API.
- Added describing icons to predetermined exercises.
=> Correct exervise lists and add part of view icon exercises

src/main/java/org/trainingTracker/database/dataAccesObject/CardioRecordsDAO.java, src/main/java/org/trainingTracker/servlets/AddCardioExercise.java, src/main/java/org/trainingTracker/servlets/SaveCardiovascularRecord.java, src/main/webapp/javascript/services.js, src/main/webapp/templates/components/cardioCard.html, src/main/webapp/templates/home.html, src/test/java/org/trainingTracker/selenium/AddCardiovascularExerciseTest.java, src/test/java/org/trainingTracker/selenium/AddPredeterminedExerciseTest.java, src/test/java/org/trainingTracker/selenium/DeleteExerciseTest.java, src/test/java/org/trainingTracker/selenium/SaveCardioRecordTest.java, src/test/java/org/trainingTracker/servlets/AddCardioExerciseServletTest.java, src/test/java/org/trainingTracker/servlets/AddExerciseServletTest.java, src/test/java/org/trainingTracker/servlets/ListPerformedServletTest.java, src/test/java/org/trainingTracker/servlets/ListRecordHistoryServletTest.java, src/test/java/org/trainingTracker/servlets/ModifyExerciseServletTest.java, src/test/java/org/trainingTracker/servlets/RemoveExerciseServletTest.java, src/test/java/org/trainingTracker/servlets/SaveRecordServletTest.java, src/test/java/org/trainingTracker/servlets/ServletTestUtils.java, src/test/java/org/trainingTracker/servlets/SignInServletTest.java, src/test/java/org/trainingTracker/servlets/SignUpServletTest.java
- Add selenium tests for SaveCardiovascularRecord #120 
- Add servlets tests with Mockito for AddCardioExercises and ListRecordHistory
- Add new documentation for several tests
- Fix couple tests to adapt to the new API
- Fix SaveCardioRedcord servlet with some errors
=> Add several new tests, new documentation for tests and couple fixes

src/main/webapp/javascript/controllers/addExerciseController.js, src/main/webapp/javascript/controllers/exerciseHistoryController.js, src/main/webapp/javascript/services.js, src/main/webapp/templates/addExercise.html, src/main/webapp/templates/exerciseHistory.html
- Correct minor fixes in custom icons.
=> Correct minor fixes

src/main/java/org/trainingTracker/database/valueObject/CardioRecordVO.java, src/main/java/org/trainingTracker/servlets/SaveCardiovascularRecord.java
Time bug fixed with setting Timezone to GMT+0, without changing it in the host.
=> CardioRecords changes
